"use client";
import { useActionState, useState } from "react";
import { Pencil, Plus } from "lucide-react";
import { createProjectAction, createTaskAction, updateProjectAction, updateTaskAction, type ActionState } from "@/app/actions";
import { Modal } from "./modal";
import { ASSIGNEES, PRIORITIES, PROJECT_STATUSES, STATUSES, type Project, type Task } from "@/lib/types";
const initial:ActionState={};

export function NewProjectButton(){
  const[open,setOpen]=useState(false);const[state,action,pending]=useActionState(createProjectAction,initial);
  return <><button className="btn" onClick={()=>setOpen(true)}><Plus size={17}/> Yeni kategori</button><Modal open={open} onClose={()=>setOpen(false)} title="Proje kategorisi oluştur"><form action={action} className="form"><ProjectFields/>{state.error&&<div className="alert">{state.error}</div>}<div className="dialog-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Vazgeç</button><button className="btn" disabled={pending}>{pending?"Oluşturuluyor…":"Kategoriyi oluştur"}</button></div></form></Modal></>;
}

function ProjectFields({project}:{project?:Project}){return <><div className="field"><label>Proje / kategori adı</label><input className="input" name="name" required defaultValue={project?.name} placeholder="Örn. Müşteri Portalı"/></div><div className="field"><label>Kısa açıklama</label><textarea className="input" name="description" defaultValue={project?.description} placeholder="Bu proje kategorisinde ne yapılacak?"/></div><div className="form-row"><div className="field"><label>Hedef tarih</label><input className="input" type="date" name="target_date" defaultValue={project?.target_date??""}/></div><div className="field"><label>Durum</label><select className="input" name="status" defaultValue={project?.status??"Planlandı"}>{PROJECT_STATUSES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="field"><label>Kategori rengi</label><input className="input" type="color" name="color" defaultValue={project?.color??"#5b5bd6"}/></div></>}

export function NewTaskButton({projects,tasks,defaultProjectId,label="Yeni madde"}:{projects:Project[];tasks:Task[];defaultProjectId?:number;label?:string}){
  const[open,setOpen]=useState(false);const[state,action,pending]=useActionState(createTaskAction,initial);
  return <><button className="btn" onClick={()=>setOpen(true)} disabled={!projects.length}><Plus size={17}/>{label}</button><Modal open={open} onClose={()=>setOpen(false)} title="Kategoriye madde ekle"><form action={action} className="form"><TaskFields projects={projects} tasks={tasks} defaultProjectId={defaultProjectId}/>{state.error&&<div className="alert">{state.error}</div>}<div className="dialog-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Vazgeç</button><button className="btn" disabled={pending}>{pending?"Ekleniyor…":"Maddeyi ekle"}</button></div></form></Modal></>;
}

function TaskFields({projects,tasks,defaultProjectId,task}:{projects:Project[];tasks:Task[];defaultProjectId?:number;task?:Task}){return <><div className="field"><label>Madde başlığı</label><input className="input" name="title" required defaultValue={task?.title} placeholder="Yapılacak işi kısa ve açık yazın"/></div><div className="field"><label>Proje kategorisi</label><select className="input" name="project_id" defaultValue={task?.project_id??defaultProjectId}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Açıklama</label><textarea className="input" name="description" defaultValue={task?.description}/></div><div className="form-row"><div className="field"><label>Durum</label><select className="input" name="status" defaultValue={task?.status??"Yapılacak"}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Öncelik</label><select className="input" name="priority" defaultValue={task?.priority??"Normal"}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="form-row"><div className="field"><label>Sorumlu kullanıcı</label><select className="input" name="assignee" defaultValue={ASSIGNEES.includes(task?.assignee as never)?task?.assignee:"meyeka"}>{ASSIGNEES.map(x=><option key={x} value={x}>{x}</option>)}</select></div><div className="field"><label>Bağımlı olduğu madde</label><select className="input" name="dependency_id" defaultValue={task?.dependency_id??""}><option value="">Bağımlılık yok</option>{tasks.filter(x=>x.id!==task?.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></div></div><div className="form-row"><div className="field"><label>Başlangıç</label><input className="input" type="date" name="start_date" defaultValue={task?.start_date??""}/></div><div className="field"><label>Teslim</label><input className="input" type="date" name="due_date" defaultValue={task?.due_date??""}/></div></div><div className="field"><label>Notlar</label><textarea className="input" name="notes" defaultValue={task?.notes} placeholder="Teknik notlar, bağlantılar veya kararlar…"/></div></>}

export function EditTaskButton({task,projects,tasks}:{task:Task;projects:Project[];tasks:Task[]}){const[open,setOpen]=useState(false);return <><button className="btn ghost" onClick={()=>setOpen(true)} aria-label="Maddeyi düzenle"><Pencil size={16}/></button><Modal open={open} onClose={()=>setOpen(false)} title="Maddeyi düzenle"><form action={updateTaskAction} className="form"><input type="hidden" name="id" value={task.id}/><TaskFields projects={projects} tasks={tasks} task={task}/><div className="dialog-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Vazgeç</button><button className="btn">Değişiklikleri kaydet</button></div></form></Modal></>}
export function EditProjectButton({project}:{project:Project}){const[open,setOpen]=useState(false);return <><button className="btn secondary" onClick={()=>setOpen(true)}><Pencil size={16}/> Düzenle</button><Modal open={open} onClose={()=>setOpen(false)} title="Kategoriyi düzenle"><form action={updateProjectAction} className="form"><input type="hidden" name="id" value={project.id}/><ProjectFields project={project}/><div className="dialog-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Vazgeç</button><button className="btn">Kaydet</button></div></form></Modal></>}
