"use client";
import { useState } from "react";
import { ChevronDown, ChevronUp, Link2, MoreHorizontal, Plus, Trash2 } from "lucide-react";
import { addSubtaskAction, deleteSubtaskAction, deleteTaskAction, moveTaskAction, toggleSubtaskAction, updateTaskFieldAction } from "@/app/actions";
import type { Task } from "@/lib/types";
import { PRIORITIES, STATUSES } from "@/lib/types";
import { ASSIGNEES } from "@/lib/types";
import { DueBadge, PriorityBadge, StatusBadge } from "./status";
export function TaskItem({task,showProject=false,sortable=false}:{task:Task;showProject?:boolean;sortable?:boolean}){const[detail,setDetail]=useState(false);return <div className="task-row"><div><button type="button" onClick={()=>setDetail(!detail)} style={{border:0,background:"none",padding:0,textAlign:"left",cursor:"pointer"}}><span className="task-title">{task.title}</span></button><div className="meta">{showProject&&<span style={{fontWeight:700,color:task.project_color}}>{task.project_name}</span>}<StatusBadge status={task.status}/><PriorityBadge priority={task.priority}/><DueBadge task={task}/>{task.assignee&&<span>{task.assignee}</span>}{task.dependency_title&&<span><Link2 size={11}/> {task.dependency_title} sonrası</span>}{task.is_sample===1&&<span className="badge sample">Örnek</span>}</div>{detail&&<div style={{marginTop:12,paddingTop:12,borderTop:"1px solid var(--line)"}}>{task.description&&<p className="subtle" style={{lineHeight:1.6}}>{task.description}</p>}{task.notes&&<p className="subtle"><b>Not:</b> {task.notes}</p>}<div className="list">{task.subtasks.map(s=><div className="check" key={s.id}><form action={toggleSubtaskAction}><input type="hidden" name="id" value={s.id}/><button className="btn ghost small" aria-label={s.completed?"Tamamlanmadı yap":"Tamamla"}>{s.completed?"✓":"○"}</button></form><span className={s.completed?"strike":""}>{s.title}</span><form action={deleteSubtaskAction} style={{marginLeft:"auto"}} onSubmit={e=>{if(!confirm("Bu alt işi silmek istediğinizden emin misiniz?"))e.preventDefault()}}><input type="hidden" name="id" value={s.id}/><button className="btn ghost small" aria-label="Alt işi sil"><Trash2 size={13}/></button></form></div>)}</div><form action={addSubtaskAction} style={{display:"flex",gap:7,marginTop:8}}><input type="hidden" name="task_id" value={task.id}/><input className="input" name="title" placeholder="Yeni alt iş" required/><button className="btn secondary small"><Plus size={14}/> Ekle</button></form></div>}</div><div style={{display:"flex",alignItems:"center",gap:5}}>{sortable&&<><form action={moveTaskAction}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="direction" value="up"/><button className="btn ghost" aria-label="Yukarı taşı"><ChevronUp size={16}/></button></form><form action={moveTaskAction}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="direction" value="down"/><button className="btn ghost" aria-label="Aşağı taşı"><ChevronDown size={16}/></button></form></>}<button className="btn ghost" onClick={()=>setDetail(!detail)} aria-label="Ayrıntılar"><MoreHorizontal size={18}/></button><form action={deleteTaskAction} onSubmit={e=>{if(!confirm(`“${task.title}” işini ve alt işlerini silmek istediğinizden emin misiniz?`))e.preventDefault()}}><input type="hidden" name="id" value={task.id}/><button className="btn ghost" aria-label="İşi sil"><Trash2 size={16}/></button></form></div></div>}
export function InlineStatus({task}:{task:Task}){return <form action={async form=>{await updateTaskFieldAction(form)}}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="field" value="status"/><select className="input" name="value" defaultValue={task.status} onChange={e=>e.currentTarget.form?.requestSubmit()} aria-label="Durumu değiştir">{STATUSES.map(x=><option key={x}>{x}</option>)}</select></form>}
export function InlinePriority({task}:{task:Task}){return <form action={async form=>{await updateTaskFieldAction(form)}}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="field" value="priority"/><select className="input" name="value" defaultValue={task.priority} onChange={e=>e.currentTarget.form?.requestSubmit()} aria-label="Önceliği değiştir">{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></form>}
export function InlineAssignee({task}:{task:Task}){return <form action={async form=>{await updateTaskFieldAction(form)}}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="field" value="assignee"/><select className="input" name="value" defaultValue={task.assignee} onChange={e=>e.currentTarget.form?.requestSubmit()} aria-label="Sorumlu kullanıcıyı değiştir">{ASSIGNEES.map(x=><option key={x}>{x}</option>)}</select></form>}
export function InlineDueDate({task}:{task:Task}){return <form action={async form=>{await updateTaskFieldAction(form)}}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="field" value="due_date"/><input className="input" type="date" name="value" defaultValue={task.due_date??""} onChange={e=>e.currentTarget.form?.requestSubmit()} aria-label="Teslim tarihini değiştir"/></form>}
