"use client";
import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckSquare2, ChevronDown, Filter, FolderKanban, GripVertical, Search, UserRound } from "lucide-react";
import { updateTaskFieldAction } from "@/app/actions";
import type { Priority, Project, Task, TaskStatus } from "@/lib/types";
import { ASSIGNEES, isOverdue, PRIORITIES, STATUSES } from "@/lib/types";
import { InlineAssignee, InlineDueDate, InlinePriority, InlineStatus } from "./task-item";
import { DueBadge, PriorityBadge } from "./status";
import { EditTaskButton, NewProjectButton, NewTaskButton } from "./forms";

export function WorkspaceBoard({projects,tasks}:{projects:Project[];tasks:Task[]}){
  const router=useRouter();
  const [localTasks,setLocalTasks]=useState(tasks),[projectId,setProjectId]=useState<number|null>(null),[query,setQuery]=useState(""),[priority,setPriority]=useState<Priority|"">(""),[assignee,setAssignee]=useState(""),[showFilters,setShowFilters]=useState(false),[draggedId,setDraggedId]=useState<number|null>(null),[dropStatus,setDropStatus]=useState<TaskStatus|null>(null),[message,setMessage]=useState("");
  const [,startTransition]=useTransition();
  useEffect(()=>setLocalTasks(tasks),[tasks]);
  const filtered=useMemo(()=>localTasks.filter(t=>(!projectId||t.project_id===projectId)&&(!query||t.title.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")))&&(!priority||t.priority===priority)&&(!assignee||t.assignee===assignee)),[localTasks,projectId,query,priority,assignee]);
  const selected=projectId?projects.find(p=>p.id===projectId):null;
  function moveTask(status:TaskStatus){if(!draggedId)return;const task=localTasks.find(t=>t.id===draggedId);if(!task||task.status===status){setDraggedId(null);setDropStatus(null);return}const previous=task.status;setLocalTasks(current=>current.map(t=>t.id===draggedId?{...t,status}:t));setMessage(`“${task.title}” → ${status}`);const form=new FormData();form.set("id",String(draggedId));form.set("field","status");form.set("value",status);startTransition(async()=>{const result=await updateTaskFieldAction(form);if(!result.success){setLocalTasks(current=>current.map(t=>t.id===draggedId?{...t,status:previous}:t));setMessage(result.error||"Madde taşınamadı.")}else router.refresh()});setDraggedId(null);setDropStatus(null)}
  return <div className="workspace-grid">
    <aside className="project-rail"><div className="rail-head"><span>PROJELER</span><NewProjectButton/></div><button className={`project-nav ${projectId===null?"selected":""}`} onClick={()=>setProjectId(null)}><span className="project-symbol all"><FolderKanban size={15}/></span><span><b>Tüm işler</b><small>{localTasks.length} iş</small></span></button>{projects.map(p=><button key={p.id} className={`project-nav ${projectId===p.id?"selected":""}`} onClick={()=>setProjectId(p.id)}><span className="project-symbol" style={{background:p.color}}>{p.name.slice(0,1).toUpperCase()}</span><span><b>{p.name}</b><small>{p.total_tasks} iş {p.is_sample===1&&"· Örnek"}</small></span></button>)}</aside>
    <section className="board-area"><div className="board-heading"><div><div className="breadcrumb">CGR İş Takip <span>/</span> {selected?.name||"Tüm projeler"}</div><h1>{selected?.name||"Tüm işler"}</h1><p>{selected?.description||"Kartları tutup başka bir sütuna sürükleyerek durumunu değiştirin."}</p></div><NewTaskButton projects={projects} tasks={localTasks} defaultProjectId={projectId??undefined}/></div><div className="board-toolbar"><label className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="İşlerde ara"/></label><button className={`toolbar-btn ${showFilters?"active":""}`} onClick={()=>setShowFilters(!showFilters)}><Filter size={15}/> Filtreler <ChevronDown size={14}/></button>{priority&&<button className="filter-chip" onClick={()=>setPriority("")}>{priority} ×</button>}{assignee&&<button className="filter-chip" onClick={()=>setAssignee("")}>{assignee} ×</button>}<span className="drag-help"><GripVertical size={14}/> Kartları sürükleyebilirsiniz</span><span className="result-count">{filtered.length} iş</span></div>{showFilters&&<div className="quick-filters"><label><span>Öncelik</span><select value={priority} onChange={e=>setPriority(e.target.value as Priority|"")}><option value="">Tümü</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Sorumlu</span><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Tümü</option>{ASSIGNEES.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn ghost small" onClick={()=>{setPriority("");setAssignee("")}}>Temizle</button></div>}{message&&<button className="move-toast" onClick={()=>setMessage("")}>{message}</button>}<div className="jira-board">{STATUSES.map(status=><BoardColumn key={status} status={status} tasks={filtered.filter(t=>t.status===status)} projects={projects} allTasks={localTasks} draggedId={draggedId} active={dropStatus===status} onDragStart={setDraggedId} onDragEnd={()=>{setDraggedId(null);setDropStatus(null)}} onDragOver={()=>setDropStatus(status)} onDrop={()=>moveTask(status)}/>)}</div></section>
  </div>
}

function BoardColumn({status,tasks,projects,allTasks,draggedId,active,onDragStart,onDragEnd,onDragOver,onDrop}:{status:TaskStatus;tasks:Task[];projects:Project[];allTasks:Task[];draggedId:number|null;active:boolean;onDragStart:(id:number)=>void;onDragEnd:()=>void;onDragOver:()=>void;onDrop:()=>void}){
  return <section className={`jira-column ${active?"drop-active":""}`} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";onDragOver()}} onDrop={e=>{e.preventDefault();onDrop()}}><header><span className={`status-dot s-${STATUSES.indexOf(status)}`}/><b>{status.toLocaleUpperCase("tr")}</b><em>{tasks.length}</em></header><div className="jira-stack">{tasks.map(task=><article draggable onDragStart={e=>{e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",String(task.id));onDragStart(task.id)}} onDragEnd={onDragEnd} className={`jira-card ${isOverdue(task)?"card-overdue":""} ${draggedId===task.id?"is-dragging":""}`} key={task.id}><div className="card-top"><span className="drag-handle" title="Sürükleyerek taşı"><GripVertical size={15}/></span><span className="project-key" style={{background:task.project_color}}>{task.project_name.slice(0,2).toLocaleUpperCase("tr")}</span><EditTaskButton task={task} projects={projects} tasks={allTasks}/></div><h3>{task.title}</h3>{task.description&&<p>{task.description}</p>}<div className="card-labels"><PriorityBadge priority={task.priority}/><DueBadge task={task}/>{task.subtasks.length>0&&<span className="subtask-count"><CheckSquare2 size={13}/>{task.subtasks.filter(x=>x.completed).length}/{task.subtasks.length}</span>}</div><div className="quick-edit"><label><span>Öncelik</span><InlinePriority task={task}/></label><label><span>Sorumlu</span><InlineAssignee task={task}/></label><label className="date-field"><span>Teslim tarihi</span><InlineDueDate task={task}/></label></div><footer><span className="assignee"><UserRound size={13}/>{task.assignee||"Atanmamış"}</span><InlineStatus task={task}/></footer>{isOverdue(task)&&<div className="overdue-line"><AlertTriangle size={12}/> Teslim tarihi geçti</div>}</article>)}{!tasks.length&&<div className="column-empty">{active?"Buraya bırakın":"Bu aşamada iş yok"}</div>}</div></section>
}
